export type DocLang = 'en' | 'zh_CN' | 'ja'

const M = {
  home: { en: 'Home', zh_CN: '首页', ja: 'ホーム' },
  gettingStarted: { en: 'Getting Started', zh_CN: '快速入门', ja: 'はじめに' },
  flexDesigner: { en: 'FlexDesigner', zh_CN: 'FlexDesigner', ja: 'FlexDesigner' },
  overview: { en: 'Overview', zh_CN: '概览', ja: '概要' },
  pageEditor: { en: 'Page Editor', zh_CN: '页面编辑器', ja: 'ページエディター' },
  keyEditor: { en: 'Key Editor', zh_CN: '按键编辑器', ja: 'キーエディター' },
  keyLibrary: { en: 'Key Library', zh_CN: '按键库', ja: 'キーライブラリ' },
  toolbar: { en: 'Toolbar', zh_CN: '工具栏', ja: 'ツールバー' },
  background: { en: 'Background', zh_CN: '背景', ja: '背景' },
  foreground: { en: 'Foreground', zh_CN: '前景', ja: '前景' },
  plugins: { en: 'Plugins', zh_CN: '插件', ja: 'プラグイン' },
  functions: { en: 'Functions', zh_CN: '功能', ja: '機能' },
  deviceControl: { en: 'Device Control', zh_CN: '设备控制', ja: 'デバイス制御' },
  flexbarSetting: { en: 'Flexbar Setting', zh_CN: 'Flexbar 设置', ja: 'Flexbar 設定' },
  flexbarSleep: { en: 'Flexbar Sleep', zh_CN: 'Flexbar 睡眠', ja: 'Flexbar スリープ' },
  input: { en: 'Input', zh_CN: '输入', ja: '入力' },
  keyboard: { en: 'Keyboard', zh_CN: '键盘', ja: 'キーボード' },
  mouse: { en: 'Mouse', zh_CN: '鼠标', ja: 'マウス' },
  keyboardMouse: { en: 'Keyboard + Mouse', zh_CN: '键盘 + 鼠标', ja: 'キーボード + マウス' },
  scrollWheel: { en: 'Scroll Wheel', zh_CN: '滚轮', ja: 'スクロールホイール' },
  multimedia: { en: 'Multimedia', zh_CN: '多媒体', ja: 'マルチメディア' },
  text: { en: 'Text', zh_CN: '文本', ja: 'テキスト' },
  textEmoji: { en: 'Text Emoji', zh_CN: '文本表情', ja: 'テキスト絵文字' },
  stickerPack: { en: 'Sticker Pack', zh_CN: '贴纸包', ja: 'ステッカーパック' },
  clipboard: { en: 'Clipboard', zh_CN: '剪贴板', ja: 'クリップボード' },
  executable: { en: 'Executable', zh_CN: '可执行', ja: '実行' },
  scripts: { en: 'Scripts', zh_CN: '脚本', ja: 'スクリプト' },
  openWebpage: { en: 'Open Webpage', zh_CN: '打开网页', ja: 'ウェブページを開く' },
  openApplication: { en: 'Open Application', zh_CN: '打开应用程序', ja: 'アプリを開く' },
  navigation: { en: 'Navigation', zh_CN: '导航', ja: 'ナビゲーション' },
  more: { en: 'More', zh_CN: '更多', ja: 'その他' },
  sequencedKeys: { en: 'Sequenced Keys', zh_CN: '序列按键', ja: 'シーケンスキー' },
  cycledKeys: { en: 'Cycled Keys', zh_CN: '循环按键', ja: 'サイクルキー' },
  systemControl: { en: 'System Control', zh_CN: '系统控制', ja: 'システム制御' },
  audioMixer: { en: 'Audio Mixer', zh_CN: '音频混音器', ja: 'オーディオミキサー' },
  volumeControl: { en: 'Volume Control', zh_CN: '音量控制', ja: '音量制御' },
  volumeMute: { en: 'Volume Mute', zh_CN: '静音', ja: '音量ミュート' },
  microphoneControl: { en: 'Microphone Control', zh_CN: '麦克风控制', ja: 'マイク制御' },
  microphoneMute: { en: 'Microphone Mute', zh_CN: '麦克风静音', ja: 'マイクミュート' },
  playPause: { en: 'Play Pause', zh_CN: '播放/暂停', ja: '再生/一時停止' },
  playbackInfo: { en: 'Playback Info', zh_CN: '播放信息', ja: '再生情報' },
  monitorBrightness: { en: 'Monitor Brightness', zh_CN: '显示器亮度', ja: 'モニター輝度' },
  monitorPower: { en: 'Monitor Power', zh_CN: '显示器电源', ja: 'モニター電源' },
  placeholder: { en: 'Placeholder', zh_CN: '占位', ja: 'プレースホルダー' },
  noFunctionKey: { en: 'No Function Key', zh_CN: '无功能键', ja: '機能なしキー' },
  spacer: { en: 'Spacer', zh_CN: '间隔', ja: 'スペーサー' },
  utilities: { en: 'Utilities', zh_CN: '实用工具', ja: 'ユーティリティ' },
  workspace: { en: 'Workspace', zh_CN: '工作区', ja: 'ワークスペース' },
  macroPlayer: { en: 'Macro Player', zh_CN: '宏播放器', ja: 'マクロプレーヤー' },
  keyboardLayoutSelector: {
    en: 'Keyboard Layout Selector',
    zh_CN: '键盘布局选择器',
    ja: 'キーボードレイアウト選択',
  },
  autoHotKey: { en: 'Auto Hot Key', zh_CN: '自动热键', ja: 'オートホットキー' },
  taskbar: { en: 'Taskbar', zh_CN: '任务栏', ja: 'タスクバー' },
  clock: { en: 'Clock', zh_CN: '时钟', ja: '時計' },
  timer: { en: 'Timer', zh_CN: '计时器', ja: 'タイマー' },
  powerControl: { en: 'Power Control', zh_CN: '电源控制', ja: '電源制御' },
  gadgets: { en: 'Gadgets', zh_CN: '小工具', ja: 'ガジェット' },
  performanceChart: { en: 'Performance Chart', zh_CN: '性能图表', ja: 'パフォーマンスチャート' },
  audioSpectrum: { en: 'Audio Spectrum', zh_CN: '音频频谱', ja: 'オーディオスペクトラム' },
  rgbStrip: { en: 'RGB Strip', zh_CN: 'RGB 灯带', ja: 'RGB ストリップ' },
  adobe: { en: 'Adobe', zh_CN: 'Adobe', ja: 'Adobe' },
  adobeGetStarted: { en: 'Get Started', zh_CN: '入门', ja: 'はじめる' },
  extendScript: { en: 'ExtendScript', zh_CN: 'ExtendScript', ja: 'ExtendScript' },
  timeline: { en: 'Timeline', zh_CN: '时间轴', ja: 'タイムライン' },
  obs: { en: 'OBS', zh_CN: 'OBS', ja: 'OBS' },
  github: { en: 'GitHub', zh_CN: 'GitHub', ja: 'GitHub' },
  stars: { en: 'Stars', zh_CN: '星标', ja: 'スター' },
  heatmap: { en: 'Heatmap', zh_CN: '热力图', ja: 'ヒートマップ' },
  minecraft: { en: 'Minecraft', zh_CN: 'Minecraft', ja: 'Minecraft' },
  inventoryMonitor: { en: 'Inventory Monitor', zh_CN: '物品栏监视', ja: 'インベントリモニター' },
  sdk: { en: 'SDK', zh_CN: 'SDK', ja: 'SDK' },
  pluginStructure: { en: 'Plugin Structure', zh_CN: '插件结构', ja: 'プラグイン構成' },
  flexCLI: { en: 'FlexCLI', zh_CN: 'FlexCLI', ja: 'FlexCLI' },
  releasePlugin: { en: 'Release Plugin', zh_CN: '发布插件', ja: 'プラグインのリリース' },
  apiReference: { en: 'API Reference', zh_CN: 'API 参考', ja: 'API リファレンス' },
  troubleshooting: { en: 'Troubleshooting', zh_CN: '故障排除', ja: 'トラブルシューティング' },
  createMyFirstProfile: {
    en: 'Create My First Profile',
    zh_CN: '创建我的第一个配置文件',
    ja: '最初のプロファイルを作成',
  },
  cannotConnect: { en: 'Cannot Connect', zh_CN: '无法连接', ja: '接続できない' },
  contentAwareControls: {
    en: 'Content Aware Controls',
    zh_CN: '内容感知控件',
    ja: 'コンテンツ連動コントロール',
  },
  firmware: { en: 'Firmware', zh_CN: '固件', ja: 'ファームウェア' },
  safeMode: { en: 'Safe Mode', zh_CN: '安全模式', ja: 'セーフモード' },
  flexgate: { en: 'Flexgate', zh_CN: 'Flexgate', ja: 'Flexgate' },
  releaseNotes: { en: 'Release Notes', zh_CN: '发行说明', ja: 'リリースノート' },
} as const

export type SidebarLabelId = keyof typeof M

export function sidebarLabel(lang: DocLang, id: SidebarLabelId): string {
  const row = M[id]
  return row[lang]
}
