name: Docs i18n update

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs-i18n.yml'
  pull_request:
    paths:
      - 'docs/**'

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          cd docs
          python -m pip install -r requirements.txt
          
      - name: Update translation templates
        run: |
          cd docs
          sphinx-build -b gettext source/ _build/gettext
          sphinx-intl update -p _build/gettext -l zh_CN
          
      - name: Commit updated PO templates
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "docs-bot"
            git config user.email "docs-bot@users.noreply.github.com"
            git add docs/source/locales/ docs/_build/gettext/
            git commit -m "chore(docs): update i18n templates"
            git push
          fi
